dataset:
  name: Amsterdam3D
  cache_dir: ./logs/cache
  dataset_path: # path/to/your/dataset
  class_weights: [183930533, 100581666, 17691733, 584752, 182871, 14806719]
  ignored_label_inds:
  - 0
  - 6
  - 8
  - 99
  num_classes: 6
  num_points: 65536
  test_result_folder: ./test
  use_cache: true
  steps_per_epoch_train: 100
  steps_per_epoch_valid: 10
model:
  name: RandLANet
  batcher: DefaultBatcher
  ckpt_path: # path/to/your/checkpoint
  dim_feature: 8
  dim_input: 6
  dim_output:
  - 16
  - 64
  - 128
  - 256
  - 512
  grid_size: 0.06
  ignored_label_inds:
  - 0
  - 6
  - 8
  - 99
  k_n: 16
  num_classes: 6
  num_layers: 5
  num_points: 65536
  sub_sampling_ratio:
  - 4
  - 4
  - 4
  - 4
  - 2
  weight_decay: 0.001
  t_augment:
    turn_on: false
    rotation_method: vertical
    scale_anisotropic: false
    symmetries: true
    noise_level: 0.001
    min_s: 0.9
    max_s: 1.1
  t_normalize:
    method: linear
    normalize_points: False
    feat_bias: 0
    feat_scale: 1
pipeline:
  name: SemanticSegmentation
  adam_lr: 0.004
  batch_size: 2
  learning_rate: 0.01
  main_log_dir: ./logs
  max_epoch: 200
  save_ckpt_freq: 5
  scheduler_gamma: 0.9886
  test_batch_size: 1
  train_sum_dir: train_log
  val_batch_size: 2
  test_continue: false
  test_compute_metric: true
